/* Themes + shared constants. Tap the palette pills in the header to switch. */

export const THEMES = {
  kite: {
    label: "Kite",
    app: "bg-white text-gray-800",
    shell: "bg-white",
    header: "bg-white/95 border-b border-gray-200",
    brand: "text-blue-600",
    card: "bg-white border border-gray-200 rounded-lg",
    innerCard: "bg-white border border-gray-200 rounded-lg",
    rowItem: "bg-gray-50 border border-gray-200 rounded-lg",
    sectionLabel: "text-[11px] uppercase tracking-widest text-gray-400 font-medium",
    input:
      "w-full bg-white border border-gray-300 rounded-md px-3 py-2.5 text-base text-gray-800 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-200 placeholder-gray-400",
    fieldLabel: "text-xs text-gray-500 mb-1",
    primaryBtn: "bg-blue-600 hover:bg-blue-700 text-white rounded-md font-medium",
    ghostBtn: "border border-gray-300 text-gray-600 hover:bg-gray-50 rounded-md",
    linkAccent: "text-blue-600",
    tabWrap: "border-b border-gray-200",
    tabOn: "text-blue-600 border-b-2 border-blue-600 font-medium",
    tabOff: "text-gray-500 border-b-2 border-transparent",
    chipBuy: "bg-blue-50 text-blue-700",
    chipSell: "bg-orange-50 text-orange-600",
    token: "bg-blue-50 text-blue-700 border border-blue-100 rounded-md",
    op: "bg-gray-100 text-gray-600 border border-gray-200 rounded-md",
    toggleOn: "bg-blue-600",
    dashed: "border border-dashed border-gray-300 text-gray-500 hover:border-blue-500 hover:text-blue-600 rounded-lg",
    footer: "bg-white/95 border-t border-gray-200",
    muted: "text-gray-400",
    body: "text-gray-700",
    exprId: "text-blue-700 font-medium", exprOp: "text-orange-600", exprNum: "text-gray-900 font-semibold", exprLogic: "text-gray-500 font-semibold",
    sheet: "bg-white rounded-t-2xl border-t border-gray-200",
    radioOn: "border-blue-600 bg-blue-50 text-gray-800",
    radioOff: "border-gray-200 text-gray-500",
    dotOn: "border-blue-600 bg-blue-600",
    statusDone: "text-green-600", statusRun: "text-orange-500", statusQueue: "text-blue-600",
    banner: "bg-green-50 border border-green-200 text-green-700",
    tableHead: "bg-gray-50 text-gray-500",
    tableRow: "border-b border-gray-100",
    chipLive: "bg-green-50 text-green-700 border border-green-200",
    chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
    chipDraft: "bg-gray-100 text-gray-500 border border-gray-200",
    font: "'Inter', system-ui, sans-serif",
  },
  soft: {
    label: "Soft",
    app: "bg-gray-100 text-slate-800",
    shell: "bg-gray-100",
    header: "bg-gray-100/95 border-b border-gray-200/70",
    brand: "text-indigo-600",
    card: "bg-white rounded-2xl shadow-sm border border-gray-100",
    innerCard: "bg-gray-50 rounded-xl border border-gray-100",
    rowItem: "bg-white rounded-xl border border-gray-100 shadow-sm",
    sectionLabel: "text-[11px] uppercase tracking-widest text-slate-400 font-semibold",
    input:
      "w-full bg-white border border-gray-200 rounded-lg px-3 py-2.5 text-base text-slate-800 focus:outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 placeholder-slate-400",
    fieldLabel: "text-xs text-slate-500 mb-1",
    primaryBtn: "bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium shadow-sm",
    ghostBtn: "border border-gray-200 text-slate-500 hover:bg-white rounded-lg",
    linkAccent: "text-indigo-600",
    tabWrap: "bg-gray-200/70 rounded-xl p-1",
    tabOn: "bg-white text-indigo-600 rounded-lg shadow-sm font-medium",
    tabOff: "text-slate-500 rounded-lg",
    chipBuy: "bg-indigo-50 text-indigo-600",
    chipSell: "bg-rose-50 text-rose-500",
    token: "bg-indigo-50 text-indigo-600 border border-indigo-100 rounded-lg",
    op: "bg-gray-100 text-slate-500 border border-gray-200 rounded-lg",
    toggleOn: "bg-indigo-600",
    dashed: "border-2 border-dashed border-gray-200 text-slate-400 hover:border-indigo-300 hover:text-indigo-600 rounded-2xl",
    footer: "bg-white/95 border-t border-gray-200 shadow-lg",
    muted: "text-slate-400",
    body: "text-slate-600",
    exprId: "text-indigo-600 font-medium", exprOp: "text-rose-500", exprNum: "text-slate-900 font-semibold", exprLogic: "text-slate-400 font-semibold",
    sheet: "bg-white rounded-t-3xl shadow-2xl",
    radioOn: "border-indigo-500 bg-indigo-50 text-slate-800",
    radioOff: "border-gray-200 text-slate-500",
    dotOn: "border-indigo-600 bg-indigo-600",
    statusDone: "text-emerald-600", statusRun: "text-amber-500", statusQueue: "text-indigo-600",
    banner: "bg-emerald-50 border border-emerald-200 text-emerald-700",
    tableHead: "bg-gray-50 text-slate-500",
    tableRow: "border-b border-gray-100",
    chipLive: "bg-emerald-50 text-emerald-600 border border-emerald-200",
    chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
    chipDraft: "bg-gray-100 text-slate-500 border border-gray-200",
    font: "'Inter', system-ui, sans-serif",
  },
  mint: {
    label: "Mint",
    app: "bg-stone-50 text-stone-800",
    shell: "bg-stone-50",
    header: "bg-stone-50/95 border-b border-stone-200",
    brand: "text-emerald-700",
    card: "bg-white rounded-xl border border-stone-200",
    innerCard: "bg-stone-50 rounded-lg border border-stone-200",
    rowItem: "bg-white rounded-lg border border-stone-200",
    sectionLabel: "text-[11px] uppercase tracking-widest text-stone-400 font-semibold",
    input:
      "w-full bg-white border border-stone-300 rounded-lg px-3 py-2.5 text-base text-stone-800 focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-100 placeholder-stone-400",
    fieldLabel: "text-xs text-stone-500 mb-1",
    primaryBtn: "bg-emerald-600 hover:bg-emerald-700 text-white rounded-full font-medium",
    ghostBtn: "border border-stone-300 text-stone-500 hover:bg-stone-100 rounded-full",
    linkAccent: "text-emerald-700",
    tabWrap: "bg-stone-200/60 rounded-full p-1",
    tabOn: "bg-white text-emerald-700 rounded-full shadow-sm font-medium",
    tabOff: "text-stone-500 rounded-full",
    chipBuy: "bg-emerald-50 text-emerald-700",
    chipSell: "bg-red-50 text-red-600",
    token: "bg-emerald-50 text-emerald-700 border border-emerald-100 rounded-full",
    op: "bg-stone-100 text-stone-500 border border-stone-200 rounded-full",
    toggleOn: "bg-emerald-600",
    dashed: "border border-dashed border-stone-300 text-stone-500 hover:border-emerald-500 hover:text-emerald-700 rounded-xl",
    footer: "bg-white/95 border-t border-stone-200",
    muted: "text-stone-400",
    body: "text-stone-600",
    exprId: "text-emerald-700 font-medium", exprOp: "text-red-500", exprNum: "text-stone-900 font-semibold", exprLogic: "text-stone-400 font-semibold",
    sheet: "bg-white rounded-t-2xl border-t border-stone-200",
    radioOn: "border-emerald-600 bg-emerald-50 text-stone-800",
    radioOff: "border-stone-200 text-stone-500",
    dotOn: "border-emerald-600 bg-emerald-600",
    statusDone: "text-emerald-600", statusRun: "text-amber-600", statusQueue: "text-emerald-700",
    banner: "bg-emerald-50 border border-emerald-200 text-emerald-700",
    tableHead: "bg-stone-100 text-stone-500",
    tableRow: "border-b border-stone-100",
    chipLive: "bg-emerald-50 text-emerald-700 border border-emerald-200",
    chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
    chipDraft: "bg-stone-100 text-stone-500 border border-stone-200",
    font: "'Inter', system-ui, sans-serif",
  },
  dusk: {
    label: "Dusk",
    app: "bg-slate-900 text-slate-200",
    shell: "bg-slate-900",
    header: "bg-slate-900/95 border-b border-slate-800",
    brand: "text-sky-400",
    card: "bg-slate-800/60 rounded-xl border border-slate-700/60",
    innerCard: "bg-slate-800 rounded-lg border border-slate-700/60",
    rowItem: "bg-slate-900/60 rounded-lg border border-slate-700/60",
    sectionLabel: "text-[11px] uppercase tracking-widest text-slate-500 font-semibold",
    input:
      "w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2.5 text-base text-slate-100 focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-900 placeholder-slate-600",
    fieldLabel: "text-xs text-slate-400 mb-1",
    primaryBtn: "bg-sky-500 hover:bg-sky-400 text-slate-950 rounded-lg font-semibold",
    ghostBtn: "border border-slate-700 text-slate-400 hover:bg-slate-800 rounded-lg",
    linkAccent: "text-sky-400",
    tabWrap: "bg-slate-800 rounded-xl p-1",
    tabOn: "bg-slate-700 text-sky-300 rounded-lg font-medium",
    tabOff: "text-slate-500 rounded-lg",
    chipBuy: "bg-sky-500/15 text-sky-300",
    chipSell: "bg-rose-500/15 text-rose-300",
    token: "bg-sky-500/10 text-sky-300 border border-sky-500/20 rounded-lg",
    op: "bg-slate-800 text-slate-400 border border-slate-700 rounded-lg",
    toggleOn: "bg-sky-500",
    dashed: "border border-dashed border-slate-700 text-slate-500 hover:border-sky-500 hover:text-sky-400 rounded-xl",
    footer: "bg-slate-900/95 border-t border-slate-800",
    muted: "text-slate-500",
    body: "text-slate-300",
    exprId: "text-sky-300 font-medium", exprOp: "text-rose-300", exprNum: "text-amber-300 font-semibold", exprLogic: "text-slate-400 font-semibold",
    sheet: "bg-slate-900 rounded-t-2xl border-t border-slate-700",
    radioOn: "border-sky-500 bg-sky-500/10 text-slate-100",
    radioOff: "border-slate-700 text-slate-400",
    dotOn: "border-sky-400 bg-sky-400",
    statusDone: "text-emerald-400", statusRun: "text-amber-400", statusQueue: "text-sky-400",
    banner: "bg-emerald-500/10 border border-emerald-500/30 text-emerald-300",
    tableHead: "bg-slate-800 text-slate-400",
    tableRow: "border-b border-slate-800",
    chipLive: "bg-emerald-500/15 text-emerald-300 border border-emerald-500/30",
    chipPaused: "bg-amber-500/15 text-amber-300 border border-amber-500/30",
    chipDraft: "bg-slate-800 text-slate-400 border border-slate-700",
    font: "'Inter', system-ui, sans-serif",
  },
  blush: {
    label: "Blush",
    app: "bg-rose-50 text-stone-800",
    shell: "bg-rose-50",
    header: "bg-rose-50/95 border-b border-rose-100",
    brand: "text-rose-500",
    card: "bg-white rounded-2xl border border-rose-100 shadow-sm",
    innerCard: "bg-rose-50/60 rounded-xl border border-rose-100",
    rowItem: "bg-white rounded-xl border border-rose-100",
    sectionLabel: "text-[11px] uppercase tracking-widest text-rose-300 font-semibold",
    input:
      "w-full bg-white border border-rose-200 rounded-lg px-3 py-2.5 text-base text-stone-800 focus:outline-none focus:border-rose-400 focus:ring-2 focus:ring-rose-100 placeholder-stone-400",
    fieldLabel: "text-xs text-stone-500 mb-1",
    primaryBtn: "bg-rose-500 hover:bg-rose-600 text-white rounded-xl font-medium shadow-sm",
    ghostBtn: "border border-rose-200 text-stone-500 hover:bg-rose-50 rounded-lg",
    linkAccent: "text-rose-500",
    tabWrap: "bg-rose-100/70 rounded-xl p-1",
    tabOn: "bg-white text-rose-500 rounded-lg shadow-sm font-medium",
    tabOff: "text-stone-500 rounded-lg",
    chipBuy: "bg-teal-50 text-teal-600",
    chipSell: "bg-rose-100 text-rose-600",
    token: "bg-rose-50 text-rose-500 border border-rose-200 rounded-lg",
    op: "bg-stone-100 text-stone-500 border border-stone-200 rounded-lg",
    toggleOn: "bg-rose-500",
    dashed: "border-2 border-dashed border-rose-200 text-stone-400 hover:border-rose-400 hover:text-rose-500 rounded-2xl",
    footer: "bg-white/95 border-t border-rose-100",
    muted: "text-stone-400",
    body: "text-stone-600",
    exprId: "text-rose-500 font-medium", exprOp: "text-teal-600", exprNum: "text-stone-900 font-semibold", exprLogic: "text-stone-400 font-semibold",
    sheet: "bg-white rounded-t-3xl shadow-2xl",
    radioOn: "border-rose-400 bg-rose-50 text-stone-800",
    radioOff: "border-rose-100 text-stone-500",
    dotOn: "border-rose-500 bg-rose-500",
    statusDone: "text-teal-600", statusRun: "text-amber-500", statusQueue: "text-rose-500",
    banner: "bg-teal-50 border border-teal-200 text-teal-700",
    tableHead: "bg-rose-50 text-stone-500",
    tableRow: "border-b border-rose-50",
    chipLive: "bg-teal-50 text-teal-600 border border-teal-200",
    chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
    chipDraft: "bg-stone-100 text-stone-500 border border-stone-200",
    font: "'Inter', system-ui, sans-serif",
  },
  ocean: {
    label: "Ocean",
    app: "bg-blue-50 text-slate-800",
    shell: "bg-blue-50",
    header: "bg-blue-50/95 border-b border-blue-100",
    brand: "text-blue-700",
    card: "bg-white rounded-2xl border border-blue-100 shadow-sm",
    innerCard: "bg-blue-50/50 rounded-xl border border-blue-100",
    rowItem: "bg-white rounded-xl border border-blue-100",
    sectionLabel: "text-[11px] uppercase tracking-widest text-blue-300 font-semibold",
    input:
      "w-full bg-white border border-blue-200 rounded-lg px-3 py-2.5 text-base text-slate-800 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 placeholder-slate-400",
    fieldLabel: "text-xs text-slate-500 mb-1",
    primaryBtn: "bg-blue-700 hover:bg-blue-800 text-white rounded-xl font-medium shadow-sm",
    ghostBtn: "border border-blue-200 text-slate-500 hover:bg-blue-50 rounded-lg",
    linkAccent: "text-blue-700",
    tabWrap: "bg-blue-100/70 rounded-xl p-1",
    tabOn: "bg-white text-blue-700 rounded-lg shadow-sm font-medium",
    tabOff: "text-slate-500 rounded-lg",
    chipBuy: "bg-cyan-50 text-cyan-700",
    chipSell: "bg-orange-50 text-orange-600",
    token: "bg-blue-50 text-blue-700 border border-blue-200 rounded-lg",
    op: "bg-slate-100 text-slate-500 border border-slate-200 rounded-lg",
    toggleOn: "bg-blue-700",
    dashed: "border-2 border-dashed border-blue-200 text-slate-400 hover:border-blue-500 hover:text-blue-700 rounded-2xl",
    footer: "bg-white/95 border-t border-blue-100",
    muted: "text-slate-400",
    body: "text-slate-600",
    exprId: "text-blue-700 font-medium", exprOp: "text-orange-600", exprNum: "text-slate-900 font-semibold", exprLogic: "text-slate-400 font-semibold",
    sheet: "bg-white rounded-t-3xl shadow-2xl",
    radioOn: "border-blue-500 bg-blue-50 text-slate-800",
    radioOff: "border-blue-100 text-slate-500",
    dotOn: "border-blue-700 bg-blue-700",
    statusDone: "text-emerald-600", statusRun: "text-amber-500", statusQueue: "text-blue-700",
    banner: "bg-emerald-50 border border-emerald-200 text-emerald-700",
    tableHead: "bg-blue-50 text-slate-500",
    tableRow: "border-b border-blue-50",
    chipLive: "bg-emerald-50 text-emerald-600 border border-emerald-200",
    chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
    chipDraft: "bg-slate-100 text-slate-500 border border-slate-200",
    font: "'Inter', system-ui, sans-serif",
  },
  graphite: {
  label: "Graphite",
  app: "bg-neutral-950 text-neutral-200",
  shell: "bg-neutral-950",
  header: "bg-neutral-950/95 border-b border-neutral-800",
  brand: "text-amber-400",
  card: "bg-neutral-900 rounded-xl border border-neutral-800",
  innerCard: "bg-neutral-950/60 rounded-lg border border-neutral-800",
  rowItem: "bg-neutral-900 rounded-lg border border-neutral-800",
  sectionLabel: "text-[11px] uppercase tracking-widest text-neutral-500 font-semibold",
  input:
    "w-full bg-neutral-950 border border-neutral-700 rounded-lg px-3 py-2.5 text-base text-neutral-100 focus:outline-none focus:border-amber-400 focus:ring-1 focus:ring-amber-500/20 placeholder-neutral-600",
  fieldLabel: "text-xs text-neutral-400 mb-1",
  primaryBtn: "bg-amber-400 hover:bg-amber-300 text-neutral-950 rounded-lg font-semibold",
  ghostBtn: "border border-neutral-700 text-neutral-400 hover:bg-neutral-800 rounded-lg",
  linkAccent: "text-amber-400",
  tabWrap: "bg-neutral-900 rounded-xl p-1 border border-neutral-800",
  tabOn: "bg-neutral-800 text-amber-300 rounded-lg font-medium",
  tabOff: "text-neutral-500 rounded-lg",
  chipBuy: "bg-amber-400/10 text-amber-300",
  chipSell: "bg-rose-500/10 text-rose-300",
  token: "bg-amber-400/10 text-amber-300 border border-amber-400/20 rounded-lg",
  op: "bg-neutral-800 text-neutral-400 border border-neutral-700 rounded-lg",
  toggleOn: "bg-amber-400",
  dashed: "border border-dashed border-neutral-700 text-neutral-500 hover:border-amber-400 hover:text-amber-300 rounded-xl",
  footer: "bg-neutral-950/95 border-t border-neutral-800",
  muted: "text-neutral-500",
  body: "text-neutral-300",
  exprId: "text-amber-300 font-medium", exprOp: "text-rose-300", exprNum: "text-neutral-100 font-semibold", exprLogic: "text-neutral-400 font-semibold",
  sheet: "bg-neutral-950 rounded-t-2xl border-t border-neutral-700",
  radioOn: "border-amber-400 bg-amber-400/10 text-neutral-100",
  radioOff: "border-neutral-700 text-neutral-400",
  dotOn: "border-amber-400 bg-amber-400",
  statusDone: "text-emerald-400", statusRun: "text-amber-300", statusQueue: "text-amber-400",
  banner: "bg-emerald-500/10 border border-emerald-500/30 text-emerald-300",
  tableHead: "bg-neutral-900 text-neutral-400",
  tableRow: "border-b border-neutral-800",
  chipLive: "bg-emerald-500/15 text-emerald-300 border border-emerald-500/30",
  chipPaused: "bg-amber-400/15 text-amber-300 border border-amber-400/30",
  chipDraft: "bg-neutral-800 text-neutral-400 border border-neutral-700",
  font: "'Inter', system-ui, sans-serif",
},
ivory: {
  label: "Ivory",
  app: "bg-amber-50 text-stone-800",
  shell: "bg-amber-50",
  header: "bg-amber-50/95 border-b border-amber-100",
  brand: "text-amber-900",
  card: "bg-white rounded-2xl border border-amber-100 shadow-sm",
  innerCard: "bg-amber-50/60 rounded-xl border border-amber-100",
  rowItem: "bg-white rounded-xl border border-amber-100",
  sectionLabel: "text-[11px] uppercase tracking-widest text-amber-700/50 font-semibold",
  input:
    "w-full bg-white border border-amber-200 rounded-lg px-3 py-2.5 text-base text-stone-800 focus:outline-none focus:border-amber-700 focus:ring-2 focus:ring-amber-100 placeholder-stone-400",
  fieldLabel: "text-xs text-stone-500 mb-1",
  primaryBtn: "bg-amber-900 hover:bg-amber-800 text-amber-50 rounded-xl font-medium shadow-sm",
  ghostBtn: "border border-amber-200 text-stone-500 hover:bg-amber-50 rounded-lg",
  linkAccent: "text-amber-900",
  tabWrap: "bg-amber-100/70 rounded-xl p-1",
  tabOn: "bg-white text-amber-900 rounded-lg shadow-sm font-medium",
  tabOff: "text-stone-500 rounded-lg",
  chipBuy: "bg-emerald-50 text-emerald-700",
  chipSell: "bg-red-50 text-red-600",
  token: "bg-amber-100/60 text-amber-900 border border-amber-200 rounded-lg",
  op: "bg-stone-100 text-stone-500 border border-stone-200 rounded-lg",
  toggleOn: "bg-amber-900",
  dashed: "border-2 border-dashed border-amber-200 text-stone-400 hover:border-amber-700 hover:text-amber-900 rounded-2xl",
  footer: "bg-white/95 border-t border-amber-100",
  muted: "text-stone-400",
  body: "text-stone-600",
  exprId: "text-amber-900 font-medium", exprOp: "text-red-600", exprNum: "text-stone-900 font-semibold", exprLogic: "text-stone-400 font-semibold",
  sheet: "bg-white rounded-t-3xl shadow-2xl",
  radioOn: "border-amber-700 bg-amber-50 text-stone-800",
  radioOff: "border-amber-100 text-stone-500",
  dotOn: "border-amber-900 bg-amber-900",
  statusDone: "text-emerald-700", statusRun: "text-amber-700", statusQueue: "text-amber-900",
  banner: "bg-emerald-50 border border-emerald-200 text-emerald-700",
  tableHead: "bg-amber-50 text-stone-500",
  tableRow: "border-b border-amber-50",
  chipLive: "bg-emerald-50 text-emerald-700 border border-emerald-200",
  chipPaused: "bg-amber-100 text-amber-800 border border-amber-200",
  chipDraft: "bg-stone-100 text-stone-500 border border-stone-200",
  font: "'Inter', system-ui, sans-serif",
},
iris: {
  label: "Iris",
  app: "bg-violet-50 text-slate-800",
  shell: "bg-violet-50",
  header: "bg-violet-50/95 border-b border-violet-100",
  brand: "text-violet-700",
  card: "bg-white rounded-2xl border border-violet-100 shadow-sm",
  innerCard: "bg-violet-50/50 rounded-xl border border-violet-100",
  rowItem: "bg-white rounded-xl border border-violet-100",
  sectionLabel: "text-[11px] uppercase tracking-widest text-violet-300 font-semibold",
  input:
    "w-full bg-white border border-violet-200 rounded-lg px-3 py-2.5 text-base text-slate-800 focus:outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100 placeholder-slate-400",
  fieldLabel: "text-xs text-slate-500 mb-1",
  primaryBtn: "bg-violet-700 hover:bg-violet-800 text-white rounded-xl font-medium shadow-sm",
  ghostBtn: "border border-violet-200 text-slate-500 hover:bg-violet-50 rounded-lg",
  linkAccent: "text-violet-700",
  tabWrap: "bg-violet-100/70 rounded-xl p-1",
  tabOn: "bg-white text-violet-700 rounded-lg shadow-sm font-medium",
  tabOff: "text-slate-500 rounded-lg",
  chipBuy: "bg-emerald-50 text-emerald-700",
  chipSell: "bg-rose-50 text-rose-500",
  token: "bg-violet-50 text-violet-700 border border-violet-200 rounded-lg",
  op: "bg-slate-100 text-slate-500 border border-slate-200 rounded-lg",
  toggleOn: "bg-violet-700",
  dashed: "border-2 border-dashed border-violet-200 text-slate-400 hover:border-violet-500 hover:text-violet-700 rounded-2xl",
  footer: "bg-white/95 border-t border-violet-100",
  muted: "text-slate-400",
  body: "text-slate-600",
  exprId: "text-violet-700 font-medium", exprOp: "text-rose-500", exprNum: "text-slate-900 font-semibold", exprLogic: "text-slate-400 font-semibold",
  sheet: "bg-white rounded-t-3xl shadow-2xl",
  radioOn: "border-violet-500 bg-violet-50 text-slate-800",
  radioOff: "border-violet-100 text-slate-500",
  dotOn: "border-violet-700 bg-violet-700",
  statusDone: "text-emerald-600", statusRun: "text-amber-500", statusQueue: "text-violet-700",
  banner: "bg-emerald-50 border border-emerald-200 text-emerald-700",
  tableHead: "bg-violet-50 text-slate-500",
  tableRow: "border-b border-violet-50",
  chipLive: "bg-emerald-50 text-emerald-600 border border-emerald-200",
  chipPaused: "bg-amber-50 text-amber-600 border border-amber-200",
  chipDraft: "bg-slate-100 text-slate-500 border border-slate-200",
  font: "'Inter', system-ui, sans-serif",
},
};

export const TIMEFRAMES = ["1m", "3m", "5m", "15m"];
export const INDICATOR_TYPES = ["SMA", "EMA", "RSI", "SUPERTREND"];
export const PRICE_FIELDS = ["Open", "High", "Low", "Close"];
export const INSTRUMENTS = ["NIFTY", "BANKNIFTY", "FINNIFTY", "SBIN (CASH)", "RELIANCE (CASH)"];
export const EXPIRY_TYPES = ["WEEKLY", "NEXT_WEEKLY", "MONTHLY"];
export const PATTERNS = [
  { name: "Bullish Engulfing", candles: 2 }, { name: "Bearish Engulfing", candles: 2 },
  { name: "Bullish Harami", candles: 2 }, { name: "Bearish Harami", candles: 2 },
  { name: "Piercing Line", candles: 2 }, { name: "Dark Cloud Cover", candles: 2 },
  { name: "Doji", candles: 1 }, { name: "Hammer", candles: 1 },
  { name: "Inverted Hammer", candles: 1 }, { name: "Shooting Star", candles: 1 },
  { name: "Marubozu", candles: 1 },
];
export const MONTH_NAMES = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN"];
export const MONTH_FULL = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];
